#### Pandas-DataFrame And Series

Pandas is a known data manipulation library in Python, widely used for data analysis and data cleanong. it provides two primary data structure: Series and DataFrame. a series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
import pandas as pd

In [5]:
# Series
# A Pandas Series is a one-dimensional array-like object that can hold any data type. it is similar to a column in a table.

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [6]:
# Create a Series from dictionary
data={'a':1,'b':2, 'c':3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [9]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [11]:
# DataFrame
# Create a Dataframe from a dictionary of list

data={
    'Name':['Love','John','Jack'],
    'Age':[25,30,35],
    'City':['Banglore','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

   Name  Age      City
0  Love   25  Banglore
1  John   30  New York
2  Jack   35   Florida
<class 'pandas.core.frame.DataFrame'>

In [49]:
# Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Love','Age':25,'City':'Banglore'},
    {'Name':'John','Age':35,'City':'New York'},
    {'Name':'Jacob','Age':45,'City':'Florida'},
]
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0   Love   25  Banglore
1   John   35  New York
2  Jacob   45   Florida
<class 'pandas.core.frame.DataFrame'>

In [50]:
# Accesing Data From Data-Frame
df

    Name  Age      City
0   Love   25  Banglore
1   John   35  New York
2  Jacob   45   Florida

In [51]:
df['Name']

0     Love
1     John
2    Jacob
Name: Name, dtype: object

In [52]:
df.loc[0]

Name        Love
Age           25
City    Banglore
Name: 0, dtype: object

In [56]:
df.iloc[0]

Name        Love
Age           25
City    Banglore
Name: 0, dtype: object

In [57]:
df

    Name  Age      City
0   Love   25  Banglore
1   John   35  New York
2  Jacob   45   Florida

In [58]:
# Accessing a Specified Element
df.at[1,'Age']

np.int64(35)

In [59]:
df.at[2,'Name']

'Jacob'

In [60]:
# Accessing a Specified Element using iat
df.iat[2,2]

'Florida'

In [62]:
# Data Manipulation With Data Frame
df

    Name  Age      City
0   Love   25  Banglore
1   John   35  New York
2  Jacob   45   Florida

In [63]:
df['Salary']=[50000,60000,70000]
df

    Name  Age      City  Salary
0   Love   25  Banglore   50000
1   John   35  New York   60000
2  Jacob   45   Florida   70000

In [68]:
# Remove a Column
df.drop('Salary',axis=1,inplace=True)

In [69]:
df

    Name  Age      City
0   Love   25  Banglore
1   John   35  New York
2  Jacob   45   Florida

In [70]:
# Add Age to the column
df['Age']=df['Age']+1
df

    Name  Age      City
0   Love   26  Banglore
1   John   36  New York
2  Jacob   46   Florida

In [73]:
df.drop(2,inplace=True)

In [74]:
df

   Name  Age      City
0  Love   26  Banglore
1  John   36  New York

In [76]:
df=pd.read_csv('sales_data.csv')
print(df.head(5))

   Transaction ID        Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum
2           10003  2024-01-03         Clothing         Levi's 501 Jeans
3           10004  2024-01-04            Books        The Da Vinci Code
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set

   Units Sold  Unit Price  Total Revenue         Region Payment Method
0           2      999.99        1999.98  North America    Credit Card
1           1      499.99         499.99         Europe         PayPal
2           3       69.99         209.97           Asia     Debit Card
3           4       15.99          63.96  North America    Credit Card
4           1       89.99          89.99         Europe         PayPal

In [84]:
# Display the data types of each column
print("Data types : \n", df.dtypes)

# Describe the DataFrame
print("Statistical summary: \n", df.describe())

Data types :
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [85]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000